# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170510_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='altura',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='peso',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
