# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20170510_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_normal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
