# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(max_length=20),
        ),
    ]
