# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
